spring.application.name=cambios
server.port=8080


fixer.api.url=https://data.fixer.io/api
fixer.api.key=952925eed960adcb513b7c7bef186c8f
fixer.api.base-currency=EUR 


# Habilitar Feign Clients
spring.cloud.openfeign.enabled=true