spring.application.name=cambios
server.port=8080


fixer.api.url=https://data.fixer.io/api
fixer.api.key=sua_chave
fixer.api.base-currency=EUR 


# Habilitar Feign Clients
spring.cloud.openfeign.enabled=true
